// Human-friendly help + example placeholder per common directive field key.
// Keyed by the field name used across the directive manifest. Purely for the
// builder UI — makes cryptic payload keys self-explanatory.
const HINTS = {
  action:          { help: 'What to do', placeholder: 'e.g. add, apply_coupon' },
  couponCode:      { help: 'Coupon code to apply', placeholder: '{{ payload.code }}' },
  discountPercent: { help: 'Discount percentage', placeholder: '10' },
  maxDiscount:     { help: 'Maximum discount amount', placeholder: '100' },
  message:         { help: 'Text shown to the user', placeholder: 'Item added to cart!' },
  level:           { help: 'Severity of the message' },
  intensity:       { help: 'Strength of the haptic buzz' },
  title:           { help: 'Title text', placeholder: 'Are you sure?' },
  text:            { help: 'Body text' },
  target:          { help: 'Destination screen or route name', placeholder: 'cart' },
  params:          { help: 'Extra data passed to the destination', placeholder: '{ "id": 42 }' },
  url:             { help: 'The URL to open / call', placeholder: 'https://example.com/...' },
  uri:             { help: 'In-app deep-link URI', placeholder: 'myapp://cart' },
  sheetId:         { help: 'Identifier of the sheet to open', placeholder: 'product_customizer' },
  modalId:         { help: 'Identifier of the modal to open', placeholder: 'confirm_order' },
  tab:             { help: 'Which tab to switch to', placeholder: 'home' },
  anchor:          { help: 'Element/anchor to scroll to', placeholder: 'reviews' },
  items:           { help: 'List of items to render', placeholder: '{{ response.body }}' },
  productId:       { help: 'Product identifier', placeholder: '{{ payload.productId }}' },
  imageUrl:        { help: 'Image URL', placeholder: '{{ payload.imageUrl }}' },
  price:           { help: 'Price', placeholder: '{{ payload.price }}' },
  quantity:        { help: 'Quantity', placeholder: '1' },
  key:             { help: 'The key to set', placeholder: 'cartCount' },
  count:           { help: 'Numeric value', placeholder: '1' },
  value:           { help: 'The value to store' },
  path:            { help: 'State path to update', placeholder: 'cart.count' },
  region:          { help: 'Named region to refresh', placeholder: 'cart' },
  name:            { help: 'Event name', placeholder: 'add_to_cart' },
  properties:      { help: 'Event properties (key/values)' },
  token:           { help: 'Auth token', placeholder: '{{ response.body.token }}' },
  user:            { help: 'User object' },
  reason:          { help: 'Why you are prompting', placeholder: 'Confirm it is you' },
  sound:           { help: 'Sound to play', placeholder: 'success' },
  actionLabel:     { help: 'Text for the action button', placeholder: 'Undo' },

  // added directives
  confirmLabel:    { help: 'Confirm button text', placeholder: 'Yes' },
  cancelLabel:     { help: 'Cancel button text', placeholder: 'Cancel' },
  onConfirm:       { help: 'Workflow alias to run if confirmed', placeholder: 'WORKFLOW_...' },
  field:           { help: 'Form field the error applies to', placeholder: 'email' },
  phone:           { help: 'Phone number to dial', placeholder: '+1234567890' },
  to:              { help: 'Recipient email address', placeholder: 'help@example.com' },
  subject:         { help: 'Email subject' },
  body:            { help: 'Body text' },
  section:         { help: 'Settings section to open', placeholder: 'notifications' },
  provider:        { help: 'Payment provider' },
  amount:          { help: 'Amount (minor units)', placeholder: '1999' },
  currency:        { help: 'Currency code', placeholder: 'USD' },
  planId:          { help: 'Subscription plan id' },
  component:       { help: 'SDUI component name', placeholder: 'product_grid' },
  props:           { help: 'Component properties (JSON)' },
  id:              { help: 'Identifier', placeholder: 'hero_banner' },
  theme:           { help: 'Theme to apply' },
  locale:          { help: 'Locale / language code', placeholder: 'en' },
  permission:      { help: 'Permission to request' },
  at:              { help: 'When to fire (ISO time)', placeholder: '2026-01-01T09:00:00Z' },
  startsAt:        { help: 'Start time (ISO)', placeholder: '2026-01-01T09:00:00Z' },
  endsAt:          { help: 'End time (ISO)' },
  location:        { help: 'Location / place' },
  filename:        { help: 'Saved file name', placeholder: 'invoice.pdf' },
  workflow:        { help: 'Workflow alias to run', placeholder: 'WORKFLOW_APPLY_COUPON' },
  ms:              { help: 'Milliseconds to wait', placeholder: '500' },
  data:            { help: 'Event data (JSON)' },
  code:            { help: 'Code / value', placeholder: '{{ payload.code }}' },
  lat:             { help: 'Latitude' },
  lng:             { help: 'Longitude' },
  orderId:         { help: 'Order identifier', placeholder: '{{ payload.orderId }}' },
  label:           { help: 'Label text' },
};

export function hintFor(key) {
  return HINTS[key] || {};
}
